-- AI weekly health report: a cached per-user, per-week narrative generated by the
-- local model. Key numbers are recomputed live from stats; only the narrative is cached.

CREATE TABLE weekly_reports (
  id BIGSERIAL PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  week_start DATE NOT NULL,          -- Monday of the covered calendar week
  content TEXT NOT NULL,             -- the AI-generated narrative
  model VARCHAR(80),                 -- which model produced it (or 'fallback')
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  UNIQUE (user_id, week_start)
);
CREATE INDEX idx_weekly_reports_user_week ON weekly_reports(user_id, week_start);
